# Part des dépenses alimentaires CARI 

## Références / Ressources

1.  CARI Manual - https://documents.wfp.org/stellent/groups/public/documents/manual_guide_proced/wfp271449.pdf

2.  Questionnaire de guide de l'évaluation des besoins essentiels https://docs.wfp.org/api/documents/WFP-0000115416/download/

*Les versions actualisées des références ne sont pas encore disponibles en français*

Deux points à souligner :

1. Des groupes/éléments alimentaires et non alimentaires peuvent être ajoutés au questionnaire ci-dessous en fonction du contexte.  L'utilisation de la structure de dénomination des variables permettra un calcul rapide et une comparabilité.

2.   Le pays peut ajouter des contraintes locales pour éviter les erreurs de saisie de données. 

### Version papier du questionnaire

Voici le module standardisé en format Word :

[RBDstandardized_questionnaire_lightexp_FR](https://github.com/WFP-VAM/RBD_Resilience_guide_FR/blob/main/questionnaires/RBDstandardized_questionnaire_lightexp_FR.docx?raw=true) 

### Version électronique du questionnaire

Voici le module standardisé sous xlsform :

[RBDstandardized_questionnaire_lightexp_FR](https://github.com/WFP-VAM/RBD_Resilience_guide_FR/blob/main/questionnaires/RBDstandardized_questionnaire_lightexp_FR.xlsx?raw=true) 


## Calcul de indicateur Part des dépenses alimentaires

### Exemple d'ensemble de données

Voici l'exemple d'un ensemble de données brutes :  
[exampledataFrancais_raw](https://github.com/WFP-VAM/RBD_Resilience_guide_FR/blob/main/example_datasets/exampledataFrancais_raw.sav?raw=true)  

### SPSS Syntax

Voici le fichier de syntaxe SPSS : 
[RBDStandardized_SPSSsyntaxExp_FR](https://github.com/WFP-VAM/RBD_Resilience_guide_FR/blob/main/syntax/RBDStandardized_SPSSsyntaxExp_FR.sps) 

### R Syntax

Voici le fichier de syntaxe R : 
[RBDstandardized_RsyntaxExp_FR](https://github.com/WFP-VAM/RBD_Resilience_guide_FR/blob/main/syntax/RBDstandardized_RsyntaxExp_FR.R) 
