# Stratégie d’adaption aux moyens d’existence  (LHCS)

Les ressources suivantes illustrent comment collecter et calculer la version légère CARI du module Stratégie d'adaptation aux moyens d'existence.

Les utilisateurs peuvent substituer les stratégies d'adaptation au stress, aux crises et aux situations d'urgence en fonction de leur contexte, de préférence à partir de la liste standard de stratégies de la page 47 du manuel CARI (ci-dessous). 

## Références / Ressources

1.  CARI Manual - https://documents.wfp.org/stellent/groups/public/documents/manual_guide_proced/wfp271449.pdf

2.  ENA Guidelines - https://docs.wfp.org/api/documents/WFP-0000074197/download/

*Les versions actualisées des références ne sont pas encore disponibles en français*


## Module CARI léger standardisé 

Nom de la variable | Etiquette des questions | Choix des réponses
---- | ------------- |------- 
LhCSIStress1 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *vendre des actifs/biens non productifs du ménage (radio, meuble, réfrigérateur, télévision, bijoux etc.)* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ? | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable
LhCSIStress2 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *Vendre plus d’animaux (non-productifs) que d’habitude* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ?  | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable
LhCSIStress3 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *Dépenser l’épargne* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ? | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable
LhCSIStress4 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *Emprunter de l’argent / nourriture auprès d’un prêteur formel /banque* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ? | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable
LhCSICrisis1 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *Réduire les dépenses non alimentaires essentielles telles que l’éducation, la santé (dont de médicaments)* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ? | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable
LhCSICrisis2 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *Vendre des biens productifs ou des moyens de transport (machine à coudre, brouette, vélo, car, etc.)* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ? | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable
LhCSICrisis3 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *Retirer les enfants de l’école* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ? | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable
LhCSIEmergency1 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *Vendre la maison ou du terrain* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ? | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable
LhCSIEmergency2 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *Mendier* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ? | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable
LhCSIEmergency3 | Au cours des 30 derniers jours, est ce qu’ un membre de votre ménage a du *Vendre les derniers animaux femelles* en raison d'un manque de nourriture ou d'argent pour acheter de la nourriture ? | 1) Non, je n'ai pas été confronté à une insuffisance de nourriture 2) Non, parce que j’ai déjà vendu ces actifs ou mené cette activité au cours des 12 derniers mois et je ne peux pas continuer à le faire 3)  Oui 4) Non applicable

### Version papier du questionnaire

Voici le module standardisé en format Word :

[RBDstandardized_questionnaireLHCS_CARI](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/questionnaires/RBDstandardized_questionnaireLHCS_CARI.docx?raw=true) 

### Version électronique du questionnaire

Voici le module standardisé sous xlsform :

[RBDstandardized_questionnaireLHCS_CARI](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/questionnaires/RBDstandardized_questionnaireLHCS_CARI.xlsx?raw=true) 


## Calcul de indicateur LHCS

### Example data set

Voici l'exemple d'un ensemble de données brutes :  
[exampledataFrancais_raw](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/example_datasets/exampledataFrancais_raw.sav?raw=true)  


### SPSS Syntax

Voici le fichier de syntaxe SPSS : 

[RBDstandardized_SPSSsyntaxLHCS_CARI_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/syntax/RBDstandardized_SPSSsyntaxLHCS_CARI_FR.sps) 

### R Syntax

Voici le fichier de syntaxe SPSS :  

[RBDstandardized_RsyntaxLHCS_CARI_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/syntax/RBDstandardized_RsyntaxLHCS_CARI_FR.R) 

## Module standardisé de stratégie d'adaptation aux moyens d'existence de l'ENA

### Version papier du questionnaire

Voici le module standardisé en format Word :

[RBDstandardized_questionnaireLHCS_ENA](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/questionnaires/RBDstandardized_questionnaireLHCS_ENA.docx?raw=true) 

### Version électronique du questionnaire

Voici le module standardisé sous xlsform :

[RBDstandardized_questionnaireLHCS_ENA](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/questionnaires/RBDstandardized_questionnaireLHCS_ENA.xlsx?raw=true) 


### Exemple de données et de syntaxe

Des exemples de données et de syntaxe pour la version ENA des stratégies d'adaptation des moyens de subsistance sont à venir.
