# Questionnaire combiné & Syntaxes pour les 5 indicateurs

Les chapitres 4 à 7 présentent les questionnaires et la syntaxe par indicateur.  Les ressources ci-dessous contiennent les questions et la syntaxe pour les 5 indicateurs de preuve directe de la sécurité alimentaire ainsi que des questions géographiques standardisées.

### Version papier du questionnaire

Voici le module standardisé en format Word :

[RBDstandardized_questionnairecombined_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/questionnaires/RBDstandardized_questionnairecombined_FR.docx?raw=true?raw=true) 

### Version électronique du questionnaire

Voici le module standardisé sous xlsform :

[RBDstandardized_questionnairecombined_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/questionnaires/RBDstandardized_questionnairecombined_FR.xlsx?raw=true) 

### Example data set

Voici l'exemple d'un ensemble de données brutes :  
[exampledataFrancais_raw](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/example_datasets/exampledataFrancais_raw.sav?raw=true)  


### SPSS Syntax

Voici le fichier syntaxique SPSS combiné pour le calcul des 5 indicateurs : 

[RBDstandardized_Rsyntaxcombined_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/syntax/RBDstandardized_Rsyntaxcombined_FR.sps) 

*Note - on cherche toujours un moyen de créer des variables ADMIN1Code & ADMIN2Code à partir des variables ADMIN1Name & ADMIN2Name dans SPSS*


### R Syntax

Voici le fichier syntaxique R combiné pour le calcul des 5 indicateurs : 

[RBDstandardized_Rsyntaxcombined_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/syntax/RBDstandardized_Rsyntaxcombined_FR.R) 

*Note - Le code R ci-dessus crée les variables ADMIN1Code & ADMIN2Code à partir des variables ADMIN1Name & ADMIN2Name*
