# Questionnaire combiné & Syntaxes  combiné

Les chapitres précédents ont illustré les questionnaires et la syntaxe indicateur par indicateur, module par module.

Ce chapitre contient une version combinée de tous les modules/indicateurs recommandés des chapitres 3 à 8 ainsi que les variables techniques/démographiques recommandées (comme le sexe du chef de ménage) à inclure au début du questionnaire.  Les indicateurs optionnels spécifiques à la résilience n'ont pas été inclus dans ce questionnaire combiné.  Les pays peuvent ajouter les modules spécifiques à la mesure de la résilience à leur questionnaire selon leurs besoins.

Le questionnaire suivant contient les questions standardisées et les modules recommandés mais il n'est pas exhaustif (les pays voudront probablement collecter des questions supplémentaires en plus).  Utilisateurs peuvent soit utiliser ce questionnaire et le compléter, soit copier ces questions (y compris la feuille de *choix*) dans leurs questionnaires/xlsforms.


### Version papier du questionnaire

Voici le module standardisé en format Word :

[RBDStandardized_questionnaire_all_FR](https://github.com/WFP-VAM/RBD_Resilience_guide_FR/blob/main/questionnaires/RBDStandardized_questionnaire_all_FR.docx?raw=true) 

### Version électronique du questionnaire

Voici le module standardisé sous xlsform :

[RBDstandardized_questionnaire_all_FR](https://github.com/WFP-VAM/RBD_Resilience_guide_FR/blob/main/questionnaires/RBDstandardized_questionnaire_all_FR.xlsx?raw=true) 



### SPSS Syntax

Voici le fichier syntaxique R combiné pour le calcul des  indicateurs FCS/FCSN, Part depense, rCSI, LhCSI: 

[RBDstandardized_Rsyntaxcombined_FR](https://github.com/WFP-VAM/RBD_Resilience_guide_FR/blob/main/syntax/RBDstandardized_Rsyntaxcombined_FR.sps) 

*Note - on cherche toujours un moyen de créer des variables ADMIN1Code & ADMIN2Code à partir des variables ADMIN1Name & ADMIN2Name dans SPSS*


### R Syntax

Voici le fichier syntaxique R combiné pour le calcul des  indicateurs -FCS/FCSN, Part depense, rCSI, LhCSI: 

[RBDstandardized_Rsyntaxcombined_FR](https://github.com/WFP-VAM/RBD_Resilience_guide_FR/blob/main/syntax/RBDstandardized_Rsyntaxcombined_FR.R) 



