# Visualisation des indicateurs directs de la sécurité alimentaire de CH

La visualisation de l'échelonnement des zones dans les cartes et les tableaux en fonction des différents indicateurs de sécurité alimentaire peut donner aux utilisateurs une chance de mieux contempler/synthétiser les résultats au cours du processus d'analyse.  Les ressources ci-dessous proposent deux méthodes de visualisation des résultats : via le Matrice Intermediare (fichier .csv) ou via le fichier d'enquête traité (.sav) .

## Visualisation des indicateurs directs de sécurité alimentaire de CH à partir de Matrice Intermediare (fichier .csv)

Après que les équipes d'enquête ont généré le .csv pour la matrice intermediare, le script R ci-dessous peut être utilisé pour créer des cartes et des tableaux des preuves directes de la sécurité alimentaire.

### Exemple de vidéo

<iframe width="750" height="400" src="https://www.youtube.com/embed/BdORJYlOEQU" frameborder="0" allowfullscreen></iframe>

*cette vidéo concerne la version anglaise, une version française sera créée mais nous espérons qu'elle illustre les informations essentielles*


### Exemple de matrice intermediare (fichier .csv)

Voici l'exemple zippé de matrice intermediare (.csv) généré à partir des processus du dernier chapitre :

[matrice_intermediaire_direct_fr](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/example_datasets/matrice_intermediaire_direct_fr.zip?raw=true) 

### Exemple de shapefiles 

Voici des shapefiles pour le Nigéria qui seront utilisés pour réaliser les cartes de notre exemple :

[NGA_shpfile](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/example_datasets/NGA_shpfile.zip?raw=true) 


### Syntaxe

Voici la syntaxe pour visualiser les indicateurs directs de sécurité alimentaire de CH
[example_CH_preliminaryFSresults_fromcsv_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/syntax/example_CH_preliminaryFSresults_fromcsv_FR.zip?raw=true) 


## Visualisation des indicateurs directs de sécurité alimentaire de CH directement à partir de l'ensemble des données traitées 

Alternativement, les équipes peuvent utiliser le script R ci-dessous pour créer des cartes et des tableaux des preuves directes de la sécurité alimentaire directement à partir de l'ensemble des données traitées.  


### Vidéo de présentation  

<iframe width="750" height="400" src="https://www.youtube.com/embed/SStPXUETQxY" frameborder="0" allowfullscreen></iframe>

*cette vidéo concerne la version anglaise, une version française sera créée mais nous espérons qu'elle illustre les informations essentielles*


### Exemple d'ensemble de données traitées


Voici un exemple d'ensemble de données traitées :
[exampledataFrancais_processed](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/example_datasets/exampledataFrancais_processed.sav?raw=true) 


### Exemple de shapefiles 

Voici des shapefiles pour le Nigéria qui seront utilisés pour réaliser les cartes de notre exemple :

[NGA_shpfile](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/example_datasets/NGA_shpfile.zip?raw=true) 


### Syntaxe

Voici la syntaxe pour visualiser les indicateurs directs de sécurité alimentaire de CH à partir de l'ensemble des données traitées :

[example_CH_preliminaryFSresults_fromspss_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/syntax/example_CH_preliminaryFSresults_fromspss_FR.zip?raw=true) 

## Dépannage et problèmes connus

- Si le pays n'a pas collecté tous les 5 indicateurs de sécurité alimentaire (FCS, HDDS, rCSI, HHS, LhCS) - les modules non collectés doivent être supprimés du code 
- Si le niveau d'analyse se situe au niveau de l'administration 1 uniquement - alors les variables ADMIN2Name et ADMIN2Code doivent être supprimées du code
- Si l'ADMIN1Name et l'ADMIN2Name n'ont pas été collectés avec des géocodes (voir chapitre 2), le code devra être modifié 
- - Si une variable de ponderation est utilisée, cette variable doit être renommée en `Weight_HH`, si les ponderation ne sont pas utilisés, le code `wt = WeightHH` doit être supprimé de la syntaxe.
- Pour les calculs des groupes de consommation alimentaire - modifier le code pour utiliser "FCSCat21" pour les seuils 21/35 ou "FCSCat28" pour les seuils 28/42, selon le cas.



