# Calcul de la matrice intermédiaire (preuve données directes sur la sécurité alimentaire)

Après que les équipes d'enquête ont traité les données (nettoyage, calcul des indicateurs et ajout de poids d'enquête), la syntaxe R ci-dessous peut être utilisée pour générer un fichier .csv des preuves de Food Security Direct qui peut être collé dans la matrice intermediare

## Exemple de vidéo 

<iframe width="750" height="400" src="https://www.youtube.com/embed/MfELnjz2G8E" frameborder="0" allowfullscreen></iframe>

*cette vidéo concerne la version anglaise, une version française sera créée mais nous espérons qu'elle illustre les informations essentielles*

## Génération d'une matrice intermédiaire

### Exemple d'ensemble de données traitées

Voici un exemple d'ensemble de données traitées :
[exampledataFrancais_processed](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/example_datasets/exampledataFrancais_processed.sav?raw=true) 

### Syntaxe

Voici la syntaxe pour générer la matrice intermediare à partir de l'ensemble des données traitées :
[matricemaker_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/syntax/matricemaker_FR.R) 


### Exemple de matrice intermediare 

Voici un fichier zippé de l'exemple de matrice intermediare (.csv) généré à partir des processus ci-dessus :
[matrice_intermediaire_direct_FR](https://github.com/WFP-VAM/RBD_FS_CH_guide_FR/blob/main/example_datasets/matrice_intermediaire_direct_FR.zip?raw=true) 

## Dépannage et problèmes connus

- Si le pays n'a pas collecté tous les 5 indicateurs de sécurité alimentaire (FCS, HDDS, rCSI, HHS, LhCS) - les modules non collectés doivent être supprimés du code 
- Si le niveau d'analyse se situe au niveau de l'administration 1 uniquement - alors les variables ADMIN2Name et ADMIN2Code doivent être supprimées du code
- Si l'ADMIN1Name et l'ADMIN2Name n'ont pas été collectés avec des géocodes (voir chapitre 2), le code devra être modifié 
- - Si une variable de ponderation est utilisée, cette variable doit être renommée en `Weight_HH`, si les ponderation ne sont pas utilisés, le code `wt = WeightHH` doit être supprimé de la syntaxe.
- Pour les calculs des groupes de consommation alimentaire - modifier le code pour utiliser "FCSCat21" pour les seuils 21/35 ou "FCSCat28" pour les seuils 28/42, selon le cas.
