---
title: "CH mars 2021 - Exemple de résultats préliminaires des preuves directes de la sécurité alimentaire"
author: "WFP and partners"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
library(sf)
library(tidyverse)
library(readxl)
library(kableExtra)
library(ggiraph)

#import matrice intermediare direct
matrice_intermediaire <- read_csv("C:\\RBD_FS_CH_guide_FR\\example_datasets\\matrice_intermediaire_direct_fr.csv")

#Import GIS files for country - and select only relevant areas
NGA_shp2 <- read_sf("C:\\RBD_FS_CH_guide_FR\\example_datasets\\NGA_shpfile\\nga_admbnda_adm2_osgof_20190417.shp") %>% filter(ADM1_EN %in% c("Borno","Adamawa","Yobe"))
NGA_shp1 <- read_sf("C:\\RBD_FS_CH_guide_FR\\example_datasets\\NGA_shpfile\\nga_admbnda_adm1_osgof_20190417.shp") %>% filter(ADM1_EN %in% c("Borno","Adamawa","Yobe"))
#Rename the adm1 & adm2codes in the GIS file
NGA_shp2 <- NGA_shp2 %>% rename(ADMIN2Code = ADM2_PCODE, ADMIN1Code = ADM1_PCODE)

#do an anti-join to see what doesnt match  
doesnt_join <- anti_join(matrice_intermediaire, NGA_shp2, by = c("ADMIN2Code"))
doesnt_join2 <- anti_join(matrice_intermediaire, NGA_shp2, by = c("ADMIN2Code"))
#after looking at what doesnt joine - do a join
Matrice_intermediaire_shp <- left_join(NGA_shp2,matrice_intermediaire, by = c("ADMIN2Code"))

#CH color codes
CH_colors = c("1" = "#c6ffc7", "2" = "#ffe718", "3" = "#e88400", "4" = "#e02d00", "5" = "#5e0803")


#maps by indicator
mapHDDS <- Matrice_intermediaire_shp %>% ggplot() +geom_sf_interactive(aes(fill = as.factor(HDDS_finalphase), tooltip = ADMIN2Name)) +theme_void() +coord_sf(datum=NA) +labs(fill="phasage du HDDS")  +scale_fill_manual(values = CH_colors) +ggtitle(label= "phasage du HDDS") +geom_sf(data=NGA_shp1,  lwd=1.5, fill=NA)
mapHHS <- Matrice_intermediaire_shp %>% ggplot()  +geom_sf_interactive(aes(fill = as.factor(HHS_finalphase), tooltip = ADMIN2Name)) +theme_void() +coord_sf(datum=NA) +labs(fill="phasage du HHS") +scale_fill_manual(values = CH_colors) +ggtitle(label= "phasage du HHS") +geom_sf(data=NGA_shp1,  lwd=1.5, fill=NA) 
mapFCG <- Matrice_intermediaire_shp %>% ggplot()+geom_sf_interactive(aes(fill = as.factor(FCG_finalphase), tooltip = ADMIN2Name)) +theme_void() +coord_sf(datum=NA) +labs(fill="phasage du FCG") +scale_fill_manual(values = CH_colors) +ggtitle(label= "phasage du FCG") +geom_sf(data=NGA_shp1,  lwd=1.5, fill=NA)
maprCSI <- Matrice_intermediaire_shp  %>%ggplot() +geom_sf_interactive(aes(fill = as.factor(rCSI_finalphase), tooltip = ADMIN2Name)) +theme_void() +coord_sf(datum=NA) +labs(fill="phasage du rCSI") +scale_fill_manual(values = CH_colors) +ggtitle(label= "phasage du rCSI") +geom_sf(data=NGA_shp1,  lwd=1.5, fill=NA)
mapLCS <- Matrice_intermediaire_shp  %>% ggplot() +geom_sf_interactive(aes(fill = as.factor(LhHCSCat_finalphase), tooltip = ADMIN2Name)) +theme_void() +coord_sf(datum=NA) +labs(fill="phasage du LhCS") +scale_fill_manual(values = CH_colors)  +ggtitle(label= "phasage du LhCS") +geom_sf(data=NGA_shp1,  lwd=1.5, fill=NA)

table <- matrice_intermediaire%>% select(ADMIN1Name, ADMIN2Name, FCG_finalphase, HDDS_finalphase, rCSI_finalphase, HHS_finalphase, LhHCSCat_finalphase)


table  <- table  %>% mutate(HDDS_finalphase = cell_spec(HDDS_finalphase, "html", color = "black", align = "c",  
background = factor(HDDS_finalphase, c("1", "2", "3", "4", "5"), 
c("#c6ffc7","#ffe718","#e88400","#e02d00", "#5e0803"))),
FCG_finalphase = cell_spec(FCG_finalphase, "html", color = "black", align = "c",  
background = factor(FCG_finalphase, c("1", "2", "3", "4", "5"), 
c("#c6ffc7","#ffe718","#e88400","#e02d00", "#5e0803"))),
HHS_finalphase = cell_spec(HHS_finalphase, "html", color = "black", align = "c",  
background = factor(HHS_finalphase, c("1", "2", "3", "4", "5"), 
c("#c6ffc7","#ffe718","#e88400","#e02d00", "#5e0803"))),
rCSI_finalphase = cell_spec(rCSI_finalphase, "html", color = "black", align = "c",  
background = factor(rCSI_finalphase, c("1", "2", "3", "4", "5"), 
c("#c6ffc7","#ffe718","#e88400","#e02d00", "#5e0803"))),
LhHCSCat_finalphase = cell_spec(LhHCSCat_finalphase, "html", color = "black", align = "c",  
background = factor(LhHCSCat_finalphase, c("1", "2", "3", "4", "5"), 
c("#c6ffc7","#ffe718","#e88400","#e02d00", "#5e0803"))))



```

```{r, echo = F}
girafe(ggobj = mapFCG)
```

```{r, echo = F}
girafe(ggobj = mapHDDS)
```

```{r, echo = F}
girafe(ggobj = maprCSI)
```

```{r, echo = F}
girafe(ggobj = mapHHS)
```


```{r, echo = F}
girafe(ggobj = mapLCS)
```





```{r , echo=FALSE}
kable(table, format = "html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```
